;;; tests.el --- Tests for lang-ocaml module -*- lexical-binding: t; -*-

;;; Commentary:

;; Unit tests for OCaml language support module.
;; Tests based on spec 039-lang-ocaml.md properties.

;;; Code:

(require 'ert)

;; Load module files from this directory
;; May fail in batch mode due to missing dependencies
(let* ((module-dir (file-name-directory (or load-file-name buffer-file-name)))
       (lib-file (expand-file-name "lib.el" module-dir))
       (init-file (expand-file-name "init.el" module-dir)))
  (condition-case nil
      (progn
        (load lib-file nil 'nomessage)
        (load init-file nil 'nomessage))
    (error nil)))

;;; P1: *.ml files open in neocaml-mode

(ert-deftest lang-ocaml-test-ml-auto-mode ()
  "P1: *.ml files should open in neocaml-mode."
  (let ((entry (assoc "\\.ml\\'" auto-mode-alist #'string=)))
    (should entry)
    (should (eq (cdr entry) 'neocaml-mode))))

;;; P2: *.mli files open in neocamli-mode

(ert-deftest lang-ocaml-test-mli-auto-mode ()
  "P2: *.mli files should open in neocamli-mode."
  (let ((entry (assoc "\\.mli\\'" auto-mode-alist #'string=)))
    (should entry)
    (should (eq (cdr entry) 'neocamli-mode))))

;;; Legacy mode symbols removed (post-rename)

(ert-deftest lang-ocaml-test-legacy-dune-config-mode-gone ()
  "`dune-config-mode' is no longer defined in `lang-ocaml/lib.el'."
  (should-not (fboundp 'dune-config-mode)))

(ert-deftest lang-ocaml-test-legacy-opam-config-mode-gone ()
  "`opam-config-mode' is no longer defined in `lang-ocaml/lib.el'."
  (should-not (fboundp 'opam-config-mode)))

;;; P4: /_build/ directories are read-only

(ert-deftest lang-ocaml-test-build-dir-readonly ()
  "P4: /_build/ directories should be configured read-only."
  (require '+corelib)
  (let ((entry (assoc "/_build/" dir-locals-directory-cache #'string-match-p)))
    ;; Directory cache may not be populated in test, check dirlocals function exists
    (should (fboundp '+dirlocals-set-regexp))))

;;; P5: Generated .opam files are read-only

(ert-deftest lang-ocaml-test-opam-generated-files-readonly ()
  "P5: An .opam buffer containing the generated marker becomes read-only.
The composition hook lives in `modules/lang-ocaml/init.el' and runs on
`opam-mode-hook' post-rename."
  (require 'opam-mode)
  (with-temp-buffer
    (insert "# This file is generated by opam-state-of-opam\nname: \"foo\"\n")
    (opam-mode)
    (should buffer-read-only)))

;;; P6: dune-project is recognized as project root marker

(ert-deftest lang-ocaml-test-project-root-marker ()
  "P6: dune-project should be in project-vc-extra-root-markers."
  (require 'project)
  (should (member "dune-project" project-vc-extra-root-markers)))

;;; P7-P8: Context-aware let bindings (Tempel functions)

(ert-deftest lang-ocaml-test-capture-let-context-defined ()
  "P7-P8: +ocaml-capture-let-context should be defined."
  (should (fboundp '+ocaml-capture-let-context)))

(ert-deftest lang-ocaml-test-maybe-in-defined ()
  "P7-P8: +ocaml-maybe-in should be defined."
  (should (fboundp '+ocaml-maybe-in)))

(ert-deftest lang-ocaml-test-maybe-in-returns-string ()
  "P7-P8: +ocaml-maybe-in should return a string."
  (let ((+ocaml--tempel-in-expr-p nil))
    (should (stringp (+ocaml-maybe-in))))
  (let ((+ocaml--tempel-in-expr-p t))
    (should (stringp (+ocaml-maybe-in)))))

(ert-deftest lang-ocaml-test-maybe-in-expr-context ()
  "P7: +ocaml-maybe-in returns \" in\" in expression context."
  (let ((+ocaml--tempel-in-expr-p t))
    (should (string= (+ocaml-maybe-in) " in"))))

(ert-deftest lang-ocaml-test-maybe-in-module-context ()
  "P8: +ocaml-maybe-in returns \"\" at module level."
  (let ((+ocaml--tempel-in-expr-p nil))
    (should (string= (+ocaml-maybe-in) ""))))

;;; P9: Org ocaml blocks use neocaml-mode

(ert-deftest lang-ocaml-test-org-src-lang-ocaml ()
  "P9: Org ocaml blocks should use neocaml-mode."
  (require 'org)
  (should (eq (cdr (assoc "ocaml" org-src-lang-modes)) 'neocaml)))

(ert-deftest lang-ocaml-test-org-src-lang-ocamli ()
  "P9: Org ocamli blocks should use neocamli-mode."
  (require 'org)
  (should (eq (cdr (assoc "ocamli" org-src-lang-modes)) 'neocamli)))

;;; Additional tests

(ert-deftest lang-ocaml-test-ocamlinit-auto-mode ()
  ".ocamlinit files should open in neocaml-mode."
  (let ((entry (assoc "\\.ocamlinit\\'" auto-mode-alist #'string=)))
    (should entry)
    (should (eq (cdr entry) 'neocaml-mode))))

(ert-deftest lang-ocaml-test-eglot-server-programs ()
  "Eglot should have server config for neocaml modes."
  (require 'eglot)
  (let ((has-ocaml nil))
    (dolist (entry eglot-server-programs)
      (when (and (consp (car entry))
                 (consp (caar entry))
                 (eq (caaar entry) 'neocaml-mode))
        (setq has-ocaml t)))
    (should has-ocaml)))

(ert-deftest lang-ocaml-test-apheleia-formatter ()
  "Apheleia should be configured for neocaml modes."
  (require 'apheleia)
  (should (eq (cdr (assq 'neocaml-mode apheleia-mode-alist)) 'ocamlformat))
  (should (eq (cdr (assq 'neocamli-mode apheleia-mode-alist)) 'ocamlformat)))

(provide 'lang-ocaml-tests)

;;; tests.el ends here
